spring:
  application:
    name: activity-service

  mongodb:
    uri: mongodb://localhost:27017/fitnessactivity


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#mongodb://localhost:27017/
